export const types = {
  ADDPOSITION: 'ADDPOSITION',
  UPDATEPOSITION: 'UPDATEPOSITION',
  DELETEPOSITION: 'DELETEPOSITION',
  ADDORDER: 'ADDORDER',
  UPDATEORDER: 'UPDATEORDER',
  DELETEORDER: 'DELETEORDER'
  };